# Generated by Django 2.2.6 on 2020-08-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=30, verbose_name='主题')),
                ('time', models.CharField(max_length=30, verbose_name='时间')),
                ('venue', models.CharField(max_length=30, verbose_name='地点')),
                ('content', models.CharField(max_length=200, verbose_name='内容')),
            ],
            options={
                'db_table': 'metting',
            },
        ),
    ]
