# Generated by Django 2.2.6 on 2020-08-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0002_hostmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostmodel',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='hostmodel',
            name='time',
            field=models.DateTimeField(max_length=30, verbose_name='时间'),
        ),
    ]
