# Generated by Django 2.2.6 on 2020-08-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0004_auto_20200824_1019'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hostmodel',
            table='meeting',
        ),
    ]
